dnsimple/dnsimple-python

dnsimple/dnsimple.py
`DNSimple` can take its configuration from either `./.dnsimple` or `~/.dnsimple`. It will prefer `./.dnsimple` first and fall back to a global config in `~/.dnsimple` if need be.
=> Read global configuration file

dnsimple/dnsimple.py, tests/test_auth.py
DNSimple supports API tokens that have access to only one domain. This implements support for these tokens.
`dns = DNSimple(domain_token=TOKEN)`
Also includes a (currently failing) test, though that'd need to be changed by @mikemaccana to use credentials and a domain that are publishable and work in the sandbox.
=> Adds support for Domain Tokens

README.markdown, dnsimple/dnsimple.py
I tried to write this patch in such a way that it should not interfere with any existing use cases.
Adds string interpolation to the `.dnsimple` file so you can use shell environment variables.
=> Adds shell environment string interpolation to .dnsimple config

.gitignore, .travis.yml, Makefile, README.markdown, README.md, circle.yml, setup.py, tests/test_auth.py
* Update readme to use code fences with implicit language
* Remove circle.tml as I don't use it
* Add deploy process to makefile
Signed-off-by: David Aronsohn <WagThatTail@Me.com>
=> Pre-1.0 release tweaks

MANIFEST.in, Makefile, README.md, dnsimple/__init__.py, dnsimple/dnsimple.py, tests/fixtures.py, tests/test_auth.py
* fix authentication docs in readme
* Implement requests.auth.BasicAuth instead of crafting header directly
* Remove `username` as it is redundant with `email` in APIv2
* clean up choosing logic
* Add a DNSimpleAuthException
* add build badge to readme
* minor fix to Manifest
* update build process
=> Refactor auth to fix basic auth & v2 auth documentation

.travis.yml
This change extends the python versions we test against as part of best practices when maintaining a public package.
=> Run test suite against 3.6, 3.8, 3.9, pypy3

dnsimple/response.py, tests/helpers.py, tests/service/services_domains_test.py
The status code was incorrectly serialized as a string in the test helpers. This has resulted in using strings to match if the status code is 204, which is inaccurate as the actual responses from the requests library would return an integer.
* status_code in responses is treated as an integer
* Update test helper to accurately serialize the response status code
* Tests are updated to reflect the change
Fixes https://github.com/dnsimple/dnsimple-python/issues/98
=> Evaluate status_code as integer in response checks

dnsimple/struct/delegation_signer_record.py, dnsimple/struct/tld.py, tests/fixtures/v2/api/createDelegationSignerRecord/created.http, tests/fixtures/v2/api/getDelegationSignerRecord/success.http, tests/fixtures/v2/api/getTld/success.http, tests/fixtures/v2/api/listDelegationSignerRecords/success.http, tests/fixtures/v2/api/listTlds/success.http, tests/service/domains_delegation_signer_records_test.py, tests/service/tlds_test.py
This PR:
* Updates the fixtures from [dnsimple-developer repo](https://github.com/dnsimple/dnsimple-developer/tree/main/fixtures/v2/api) to reflect the latest changes to our DNSSEC-related APIs.
* Adds new fields to affected structs.
* Updates documentation on affected endpoints.
* Updates some tests to make more clear what data is being passed in.
I was able to verify the changes by enabling DNSSEC on one of our testing .BE domains.
=> Add support for key-data interface creating delegation signer records

.github/workflows/release.yml, CONTRIBUTING.md
Adds the automated release workflow.
When a new tag is pushed the release workflow will pick it up and start the releasing of the new version.
Things that need to be done (configuration wise), which I have no access to (we need someone with admin rights on this repo for that):
=> Automate release process

dnsimple/response.py, dnsimple/struct/contact.py, dnsimple/struct/template.py, dnsimple/struct/template_record.py, dnsimple/struct/webhook.py, tests/service/contacts_test.py, tests/service/template_records_test.py, tests/service/templates_test.py, tests/service/webhooks_test.py
The `attach_attributes_to` function in `dnsimple.extra` is called in the `__init__` a few structs. The argument for `cls` passed through is `self.__class__`. This causes the class to be overwritten when multiple are created from the `return_list_of` in `response`.
Eg.
```
contact_list = client.contacts.list_contacts(account_id)
for contact in contact_list.data:
... print(contact.id)
...
12345
12345
12345
```
The classes affected are as follows:
- contacts
- webhook
- template_record
- template
- pagination
I have added tests for all classes listed except for pagination. There is only ever a single pagination object so a test is not relevant but making the way that `attach_attribute_to` consistent between classes is ideal.
Thanks for all of your help.
=> Fix attach_attributes_to call from class init

dnsimple/service/certificates.py, dnsimple/struct/certificate.py
We no longer require a contact_id to be provided to be able to purchase a Lets Encrypt certificate.
This one is a little trickier than other clients because of the the way we build the attributes to be used to purchase a LetsEncrypt certificate in `LetsencryptCertificateInput`. I have added a deprecation warning, while trying not to introduce any breaking changes.
=> No longer require `contact_id` to purchase LetsEncrypt certificates

.github/workflows/ci.yml, .github/workflows/release.yml
This PR ensures that the CI check is passing before releasing the package.
The selected approach is it use the Checks API via a community action [wait-on-check](https://github.com/marketplace/actions/wait-on-check). The action would check the default branch in our case that being **main**, and if the CI check has not yet passed it will hold the workflow execution until a result is out for the check and it can either fail or pass.
The following configuration is used for the Checks action:
```yaml
uses: lewagon/wait-on-check-action@v1.0.0
with:
ref: 'refs/heads/main'
running-workflow-name: 'Publish to PyPI'
repo-token: ${{ secrets.GITHUB_TOKEN }}
wait-interval: 10
allowed-conclusions: success
```
* Default branch ref is hard coded
* `running-workflow-name` is used with the current workflow …
=> Ensures that the CI check is passing before releasing the package

.tool-versions, dnsimple/exceptions.py
Exception class initializes `super` and overrides `__str__` method. Previously the exception was not initialized correctly and the message was never printed as it normally should, this means that when reading stack traces, the developer would not see the reason why the exception was raised.
Belongs to #209 
Exception with errors:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/dnsimple-python/dnsimple/service/zones.py", line 154, in create_record
return Response(response, ZoneRecord)
File "/dnsimple-python/dnsimple/response.py", line 43, in __init__
raise DNSimpleException(message=message, errors=errors)
dnsimple.exceptions.DNSimpleException: Validation failed: content
>>>
```
Exception with empty errors:
```
Traceback (most recent call last):
File …
```
=> Exceptions print their error message

CHANGELOG.md, dnsimple/exceptions.py, dnsimple/response.py, tests/exception_test.py, tests/service/domains_delegation_signer_records_test.py, tests/service/registrar_test.py
Our error responses sometimes include an `errors` entry with details about errors on the attributes of the specific resource. We handle those and other HTTP errors via `DNSimpleException`, but we were only considering the message, and the errors handling them in an unsafe way.
This PR:
- Renames exceptions `errors` field to `attribute_errors`
- Safe handle of error responses that have no body
- Added `reason`, `status` and `response` fields to exceptions
- Updates the exception string serialization format
=> Expose all information available in error responses

dnsimple/exceptions.py, tests/exception_test.py
Previously in #340 the `errors` attribute of `DNSimpleException` was entirely removed introducing a breaking change. In favor of keeping things backward compatible and allowing users to update their code gradually, the `errors` attribute has been brought back with deprecation warnings.
=> Deprecate errors attr with warning

CHANGELOG.md, requirements.txt
This PR fixes the security issue CVE-2022-42969. https://github.com/pytest-dev/py/issues/287#issuecomment-1290407715
The py package has been removed from the requirements as a direct dependency.
=> Drop py as direct dependency as pytest vendors it

dnsimple/service/certificates.py, dnsimple/struct/__init__.py, dnsimple/struct/certificate.py, tests/service/certificates_test.py
Add the signature_algorithm parameter for purchase_letsencrypt_certificate and purchase_letsencrypt_certificate_renewal APIs.
=> Implement signature_algorithm parameter for Let's Encrypt APIs

.github/workflows/release.yml
We don't need to pin the Python version to `3.8.5` specifically. It's out of date and `ubuntu-22.04` doesn't have it (newer patch releases are available). We'll also pin our Ubuntu version to avoid unexpected versioning issues in the future.
=> Unpin Python version and pin Ubuntu version in release CI

CHANGELOG.md, dnsimple/service/domains.py, dnsimple/service/zones.py, tests/fixtures/v2/api/activateZoneService/success.http, tests/fixtures/v2/api/deactivateZoneService/success.http, tests/service/zones_test.py
This PR implements https://github.com/dnsimple/dnsimple-developer/pull/502 which allows for the management of DNS resolution for a particular zone.
Belongs to https://github.com/dnsimple/dnsimple-external-integrations/issues/3
Belongs to https://github.com/dnsimple/dnsimple-external-integrations/issues/2
=> Add support to activate and deactivate DNS services for a zone

CHANGELOG.md, CONTRIBUTING.md, dnsimple/response.py, dnsimple/service/registrar.py, dnsimple/struct/__init__.py, dnsimple/struct/registrant.py, tests/fixtures/v2/api/checkRegistrantChange/success.http, tests/fixtures/v2/api/createRegistrantChange/success.http, tests/fixtures/v2/api/deleteRegistrantChange/success.http, tests/fixtures/v2/api/getRegistrantChange/success.http, tests/fixtures/v2/api/listRegistrantChanges/success.http, tests/service/registrar_registrant_test.py
This PR introduces 5 new endpoints that are part of the domain contact management API that was introduced in https://github.com/dnsimple/dnsimple-developer/pull/501.
The following endpoints have been added:
- **listRegistrantChanges**: GET `/{account}/registrar/registrant_changes`
- **createRegistrantChange**: POST `/{account}/registrar/registrant_changes`
- **checkRegistrantChange**: POST `/{account}/registrar/registrant_changes/check`
- **getRegistrantChange**: GET `/{account}/registrar/registrant_changes/{registrantchange}`
- **deleteRegistrantChange**: DELETE `/{account}/registrar/registrant_changes/{registrantchange}`
Belongs to https://github.com/dnsimple/dnsimple-business/issues/1729
=> Add support to create a registrant change

.tool-versions, dnsimple/client.py, dnsimple/service/__init__.py, dnsimple/service/billing.py, dnsimple/struct/__init__.py, dnsimple/struct/charge.py, tests/fixtures/v2/api/listCharges/fail-400-bad-filter.http, tests/fixtures/v2/api/listCharges/fail-403.http, tests/fixtures/v2/api/listCharges/success.http, tests/helpers.py, tests/service/billing_test.py
This adds support for the `listCharges` API.
Belongs to https://github.com/dnsimple/dnsimple-business/issues/1763
=> Implement billing charges API

CHANGELOG.md, dnsimple/struct/zone.py, tests/fixtures/v2/api/getZone/success.http, tests/fixtures/v2/api/listZones/success.http, tests/service/zones_test.py
This PR adds [missing attributes](https://github.com/dnsimple/dnsimple-developer/pull/542) of the Zone response:
- `secondary`, `last_transferred_at`, `active` to `Zone` struct
Belongs to https://github.com/dnsimple/dnsimple-external-integrations/issues/17
=> Add missing attributes to the Zone API responses

dnsimple/service/registrar.py, dnsimple/struct/__init__.py, dnsimple/struct/domain_restore.py, tests/fixtures/v2/api/getDomainRestore/success.http, tests/fixtures/v2/api/restoreDomain/success.http, tests/service/registrar_test.py
Belongs to https://github.com/dnsimple/dnsimple-business/issues/1654.
This adds two methods to the library: (1) `RestoreDomain` and (2) `GetDomainRestore`. The API endpoint implementation is in https://github.com/dnsimple/dnsimple-app/pull/25863.
=> Add restore domain endpoints

CHANGELOG.md, dnsimple/service/domains.py, dnsimple/struct/email_forward.py, tests/fixtures/v2/api/createEmailForward/created.http, tests/fixtures/v2/api/getEmailForward/success.http, tests/fixtures/v2/api/listEmailForwards/success.http, tests/service/domains_email_forwards_test.py
See https://github.com/dnsimple/dnsimple-developer/issues/315 for reference
In this PR:
- Add `alias_email` and `destination_email` fields to `EmailForward`
- Deprecate `email_from` and `email_to` fields in `EmailForward
- Align `EmailForwardInput` constructor param names with current endpoint definition
=> Update `EmailForward` fields

.markdownlint.yaml
Align with the other configs. There's an extra rule that it's not clear why it was set.
=> markdownlint: Align with other configs

dnsimple/struct/zone_record.py, tests/struct/zone_record_test.py
Fixes https://github.com/dnsimple/dnsimple-python/issues/451.
When creating a `ZoneRecordInput` and `ZoneRecordUpdateInput` with `name=''`, the `to_json()` command omits the `name` attribute because of the `omitempty` command. The `omitempty` [command](https://github.com/bfontaine/omitempty) removes empty strings by default.
This PR changes the behavior to allow a name with an empty string to be rendered by the `to_json` command. This name with an empty string represents an apex record.
=> Allow empty string to represent apex records
